"""AqBanking command runner and parsers."""

from __future__ import annotations

import csv
import datetime as dt
import getpass
import os
import re
import subprocess
import tempfile
from collections.abc import Iterator
from contextlib import contextmanager
from dataclasses import dataclass
from pathlib import Path

from .security import validate_fints_pin


@dataclass(frozen=True)
class AqContext:
    root: Path

    @property
    def cfg_dir(self) -> Path:
        return self.root / "config" / "aqbanking.local"

    @property
    def home_dir(self) -> Path:
        return self.root / "config" / "aqbanking.home.local"

    @property
    def data_dir(self) -> Path:
        return self.root / "data"

    @property
    def context_file(self) -> Path:
        return self.data_dir / "aqbanking.ctx"

    def prepare(self) -> None:
        self.cfg_dir.mkdir(parents=True, exist_ok=True)
        self.home_dir.mkdir(parents=True, exist_ok=True)
        self.data_dir.mkdir(parents=True, exist_ok=True)


def base(ctx: AqContext, tool: str) -> list[str]:
    return [tool, f"--cfgdir={ctx.cfg_dir}", "--acceptvalidcerts"]


def aq_env(ctx: AqContext) -> dict[str, str]:
    env = os.environ.copy()
    env["HOME"] = str(ctx.home_dir)
    env["AQBANKING_LOGLEVEL"] = "error"
    env.pop("AQBANKING_STORE_JOBLOGS", None)
    return env


def user_config_path(ctx: AqContext, unique_user_id: str) -> Path:
    return ctx.cfg_dir / "settings6" / "users" / f"{int(unique_user_id):08d}.conf"


def read_aq_value(path: Path, key: str) -> str:
    pattern = re.compile(rf'^\w+\s+{re.escape(key)}="(.*)"$')
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        match = pattern.match(line.strip())
        if match:
            return match.group(1)
    raise ValueError(f"Could not find {key} in {path}.")


def quote_pin_value(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


@contextmanager
def temporary_pinfile(ctx: AqContext, unique_user_id: str) -> Iterator[Path]:
    path = user_config_path(ctx, unique_user_id)
    if not path.exists():
        raise ValueError(f"Unknown AqBanking user id: {unique_user_id}")
    bank_code = read_aq_value(path, "bankCode")
    user_id = read_aq_value(path, "userId")
    pin = getpass.getpass(f"PIN for AqBanking user {unique_user_id}: ")
    validate_fints_pin(pin)

    handle = tempfile.NamedTemporaryFile("w", encoding="utf-8", delete=False)
    pinfile = Path(handle.name)
    try:
        os.chmod(pinfile, 0o600)
        handle.write("# Temporary AqBanking PIN file generated by finlocal.\n")
        handle.write(f'PIN_{bank_code}_{user_id} = "{quote_pin_value(pin)}"\n')
        handle.close()
        yield pinfile
    finally:
        try:
            pinfile.unlink()
        except FileNotFoundError:
            pass


def run_interactive(ctx: AqContext, args: list[str]) -> int:
    ctx.prepare()
    return subprocess.run(args, env=aq_env(ctx), check=False).returncode


def run_capture(ctx: AqContext, args: list[str]) -> str:
    ctx.prepare()
    result = subprocess.run(args, env=aq_env(ctx), text=True, capture_output=True, check=False)
    if result.returncode != 0:
        raise RuntimeError((result.stdout + "\n" + result.stderr).strip())
    return result.stdout


def run_with_optional_pinfile(ctx: AqContext, command: list[str], unique_user_id: str | None) -> int:
    if not unique_user_id:
        return run_interactive(ctx, command)
    with temporary_pinfile(ctx, unique_user_id) as pinfile:
        return run_interactive(ctx, command[:1] + [f"--pinfile={pinfile}", *command[1:]])


def parse_balance_output(output: str, snapshot_date: str) -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    for line in output.splitlines():
        parts = line.split("\t")
        if len(parts) != 5:
            continue
        balance_date, value, iban, bank_code, account_number = parts
        rows.append(
            {
                "date": snapshot_date,
                "source": "AqBanking",
                "balance_date": balance_date,
                "balance": value,
                "iban": iban,
                "bank_code": bank_code,
                "account_number": account_number,
                "exported_at": dt.datetime.now(dt.timezone.utc).isoformat(),
            }
        )
    return rows


def append_csv(path: Path, rows: list[dict[str, str]]) -> None:
    if not rows:
        print("No rows exported.")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    exists = path.exists()
    with path.open("a", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0].keys()))
        if not exists:
            writer.writeheader()
        writer.writerows(rows)
    print(f"Appended {len(rows)} row(s) to {path}.")

